image:
  tag: "1.23"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    nginx.ingress.kubernetes.io/rewrite-target: /  
  hosts:
    - host: "srv-prod.test"
      paths:
        - path: /
          pathType: Prefix
