image:
  tag: "1.23"

ingress:
  enabled: true
  hosts:
    - host: srv-prod.test
      paths:
        - path: /
          pathType: Prefix

configmap:
  name: configmap-dev
  path: /usr/share/nginx/html
  volume: nginx-index-file
  file: index.html
  data: |
    <html>
    <h1>Prod Server</h1>
    </html