configmap:
  name: configmap-dev
  path: /usr/share/nginx/html
  volume: nginx-index-file
  file: index.html
  data:
    <html>
    <h1>Dev Server</h1>
    </html>
    
image:
  tag: "1.23"

ingress:
  enabled: true
  hosts:
    - host: srv-dev.test
      paths:
        - path: /
          pathType: Prefix


